<?php

namespace ContainerLCWuuYo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GMzsjKNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GMzsjKN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GMzsjKN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'diplomasRepository' => ['privates', 'App\\Repository\\DiplomasRepository', 'getDiplomasRepositoryService', true],
        ], [
            'diplomasRepository' => 'App\\Repository\\DiplomasRepository',
        ]);
    }
}
