<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWCZisDp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWCZisDp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWCZisDp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWCZisDp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWCZisDp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WCZisDp',
    'container.build_id' => '85b6d90d',
    'container.build_time' => 1619983192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWCZisDp');
